% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Empirical Analysis of Airbnb Listing Prices in Boston, USA},
  pdfauthor={Riley Fewer, Polyna German, Arya Badal Kalarickal, Omar Salaheldin Shahata},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Empirical Analysis of Airbnb Listing Prices in Boston, USA}
\author{Riley Fewer, Polyna German, Arya Badal Kalarickal, Omar
Salaheldin Shahata}
\date{April 3, 2026}

\begin{document}
\maketitle

\subsection{Section 1: Introduction}\label{section-1-introduction}

Short-term rental platforms such as Airbnb have significantly impacted
tourism and housing markets. In cities like Boston, where housing supply
is limited but demand is high due to tourism and overall desirability,
understanding what drives variation in Airbnb listing prices is both
relevant and important for hosts, guests, and policymakers. Airbnb
pricing influences host revenue, market accessibility, and the
relationship between short-term rentals and long-term housing
availability. As a result, identifying the factors associated with
Airbnb prices contributes to broader discussions in real estate and
urban economics.

This project investigates the following research question: \textbf{To
what extent do property type, capacity, and listing characteristics
explain variation in the log-transformed nightly price of Airbnb
listings in Boston?} The response variable of interest is the logarithm
of the nightly listing price. The log transformation is used because
nightly Airbnb prices exhibit a strongly right-skewed distribution and
taking the logarithm of price helps better satisfy the linear regression
assumptions of linearity, constant variance, and approximately normally
distributed residuals. The preliminary model included six predictors:
number of bedrooms, number of bathrooms, number of guests accommodated,
property type, security deposit, and superhost status. These variables
capture key dimensions of physical size, guest capacity, and listing
characteristics. Through model selection, superhost status was
subsequently removed, yielding a final model with five predictors.

Existing academic literature provides motivation for this analysis.
Prior research demonstrates a strong relationship between property size,
capacity, and Airbnb prices. Cai et al.~(2019) finds that nightly Airbnb
prices in Hong Kong increase with property size and capacity, reporting
that entire homes and private rooms are priced 377\% higher than shared
rooms and that each additional bedroom increases price by approximately
17.8\%. Similarly, Gibbs et al.~(2018) finds that private rooms are
priced 28.3\% and 40.1\% lower than entire homes in Toronto and Calgary,
respectively, highlighting the premium hosts place on privacy. Barron et
al.~(2020) provides broader market context, showing that a 1\% increase
in Airbnb listings is associated with higher housing prices and rental
rates.

Linear regression is well-suited for this analysis because it allows for
the simultaneous examination of multiple numerical and categorical
predictors while maintaining interpretability. Furthermore, the
continuous nature of the log-transformed response variable supports
meaningful interpretation of estimated coefficients as percentage
changes in price.

\subsection{Section 2: Data
Description}\label{section-2-data-description}

The dataset used for our research project - Boston Airbnb Open Data
published on Kaggle (Boston Airbnb Open Data, n.d.) originates from
Inside Airbnb, a project aimed at providing data on Airbnb's impact on
residential communities (Inside Airbnb, n.d). For this project, we used
the publicly available data provided to determine how property
characteristics explain variation in the log-transformed nightly price
of Airbnb listings in Boston. The data was originally gathered by
web-scraping Airbnb listings pages (Inside Airbnb, n.d.).

The response variable is the logarithm of the nightly listing price
(log\_price). The log transformation is used because prices exhibit a
strongly right-skewed distribution (Figure 1A), causing both
non-normality and heteroskedasticity. Therefore, taking the logarithm of
price better satisfies the linear regression assumptions of linearity,
constant variance, and approximately normally distributed residuals,
making log\_price a suitable continuous response variable for our linear
regression model (Figure 1B). Of the 3,585 raw listings, 2,243 had
missing values for security\_deposit, which were set to zero on the
basis that a missing deposit indicates no requirement, consistent with
Airbnb listing practice. After removing observations with missing values
for price, bedrooms, or bathrooms, the cleaned dataset contains 3,561
observations.

The preliminary model included six predictor variables: number of
bedrooms, number of bathrooms, guests accommodated, security deposit,
property type, and superhost status. Of these, superhost status was
removed during model selection in Section 4, resulting in a final model
with five predictors.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig1-1.pdf}}
\caption{Figure 1: A) Raw nightly price distribution showing strong
right skew. B) Log-transformed price distribution showing approximate
symmetry, justifying the log transformation.}
\end{figure}

Figure 2A shows that the majority of listings do not charge a security
deposit. Figure 2B shows a highly right-skewed distribution of non-zero
deposits, with the majority of amounts being between \$100 and \$500.
According to Ert et al.~(2016), listings with higher value and quality
often include deposits, which indirectly correlate with higher pricing.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig2-1.pdf}}
\caption{Figure 2: A) Count of listings with and without a security
deposit. The majority require no deposit. B) Distribution of non-zero
deposit amounts, showing right skew with most values between \$100 and
\$500.}
\end{figure}

Figures 3A, 3B, and 3D show the distributions of bedrooms, bathrooms,
and guests\_included. These variables are discrete and right-skewed.
According to Wang and Nicolau (2017), larger properties with more
bedrooms and bathrooms affect nightly rates due to increased comfort and
accommodation capacity. Figure 3C shows that superhost status is rare.
Superhosts can charge relatively high prices because the badge functions
as a quality signal that reduces uncertainty and increases consumer
trust (Almeida et al., 2025). Figure 3E displays the major trend of
property type to be an apartment. Amenities and increased privacy play a
major role in pricing according to Gibbs et al.~(2018).

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig3-1.pdf}}
\caption{Figure 3: Distributions of all predictor variables. A)
Bedrooms, B) Bathrooms, C) Superhost status, D) Guests included, E)
Property type. All continuous predictors are right-skewed. Apartments
dominate the property type distribution.}
\end{figure}

\subsection{Section 3: Primary Model Results and
Diagnostics}\label{section-3-primary-model-results-and-diagnostics}

The preliminary linear regression estimated the logarithmic nightly
prices of Airbnb listings in Boston using the six predictors mentioned
above. The initial model explains a meaningful portion of price
variation with an adjusted \(R^2\) of 0.273. The joint significance of
the predictors is confirmed by the F-statistic of 191.5 (\(p < 0.001\)).

Consistent with hedonic pricing models (Gibbs et al., 2018; Wang \&
Nicolau, 2017), larger listings have higher rates. Each additional
bedroom and bathroom is associated with a 28.6\% and 13.6\% increase in
nightly price respectively. The bedroom effects align with Cai's (2019)
findings of a 17.8\% increase in Hong Kong, though our stronger estimate
likely reflects Boston's premium urban landscape. Guest capacity also
has a significantly positive effect, consistent with literature.
Security deposits exhibit a small but statistically significant positive
association with price, serving as a signal for listing quality (Ert et
al., 2016). Among the categorical variables, property type plays a
significant role. Houses are priced lower than apartments, contrasting
with Gibbs et al.'s (2018) findings in Toronto and Calgary where entire
homes commanded premiums. This reversal could be attributed to Boston's
apartment-centric urban core. Superhost status is not statistically
significant in the preliminary model, differing from Almeida et al.~
(2025) and suggesting physical characteristics dominate reputational
signals in Boston's mature market.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Table 1: Primary model regression coefficients. Reference
category for property type is Apartment.}\tabularnewline
\toprule\noalign{}
Predictor & Estimate & Std. Error & t-value & p-value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Predictor & Estimate & Std. Error & t-value & p-value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept & 4.3508 & 0.0268 & 162.219 & 0.0000 \\
Bedrooms & 0.2842 & 0.0150 & 18.921 & 0.0000 \\
Bathrooms & 0.1384 & 0.0212 & 6.536 & 0.0000 \\
Guests Included & 0.0809 & 0.0097 & 8.337 & 0.0000 \\
Condominium vs Apt & -0.0001 & 0.0383 & -0.002 & 0.9982 \\
House vs Apt & -0.4780 & 0.0267 & -17.927 & 0.0000 \\
Other vs Apt & -0.0733 & 0.0436 & -1.681 & 0.0929 \\
Superhost (t vs f) & -0.0178 & 0.0297 & -0.601 & 0.5480 \\
Security Deposit & 0.0002 & 0.0000 & 6.319 & 0.0000 \\
\end{longtable}

\begin{longtable}[]{@{}ll@{}}
\caption{Table 2: Primary model fit statistics.}\tabularnewline
\toprule\noalign{}
Statistic & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Statistic & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R-squared & 0.2742 \\
Adjusted R-squared & 0.2726 \\
F-statistic & 167.77 \\
p-value & \textless{} 0.001 \\
N & 3561 \\
\end{longtable}

Regression diagnostics indicate linear model assumptions are reasonable
but imperfect. The residuals are clustered around zero, suggesting that
linearity holds well, though slight curvature exhibits mild
heteroskedasticity for higher fitted values. The Scale-Location plot
confirms some variance instability. The Q-Q plot reveals upper-tail
deviations, indicating mild departures from normality. Given the large
sample size, these minor violations are unlikely to substantially bias
estimates, but motivated the model refinements described in Section 4.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig4-1.pdf}}
\caption{Figure 4: Residual diagnostic plots for the primary model.
Left: Residuals vs Fitted showing approximate linearity with mild
heteroskedasticity at higher fitted values. Centre: Q-Q plot showing
mild upper-tail deviation from normality. Right: Scale-Location plot
confirming mild variance instability.}
\end{figure}

\subsection{Section 4: Model Selection}\label{section-4-model-selection}

The final model was reached by three main decisions: Box-Cox
transformation, outlier handling, and variable selection.

The log transformation of the response variable (nightly price) was
formally confirmed using a Box-Cox power transformation analysis, which
returned \(\lambda = 0.039\). Since \(\lambda \approx 0\) corresponds to
a log transformation, this provides statistical justification for the
choice motivated in Section 2 by the right-skewed raw price distribution
(Figure 1). For the continuous predictors, two transformation candidates
were evaluated using AIC as the criterion. First, replacing
security\_deposit with \(\log(1 + \text{security\_deposit})\), which
handles the large number of zero-deposit listings (as can be seen in
Figure 2A), was tested against the primary model. The transformed model
produced an AIC of 5977.72, compared to 5942.12 for the untransformed
version, an increase of 35.6 points. The Scale-Location plots for both
specifications were visually identical (Figure 5), confirming no
heteroskedasticity improvement. Second, applying \(\log(1 + x)\) to both
bedrooms and bathrooms was tested; this worsened the AIC by 131.0 points
(AIC = 6073.12 versus 5942.12). In conclusion, no predictor
transformations were applied, so all of the predictors used in the model
are on their original scale. The decision to not transform predictors
also keeps the straightforward percentage-change interpretation of
coefficients in the log-response model.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig5-1.pdf}}
\caption{Figure 5: Scale-Location plots comparing the primary model
using raw security deposit (left) and log1p(security deposit) (right).
The smoother trend and residual spread are nearly identical across both
plots, providing no evidence that the transformation improves
homoscedasticity.}
\end{figure}

The primary model's Cook's Distance plot (Figure 6) and influence plot
(Figure 7) were used to identify observations that disproportionately
affected the fitted coefficients. Leverage values were computed and
compared against the Hoaglin and Welsch (1978) threshold of
\(2(p+1)/n = 2(9)/3{,}561 \approx 0.005\), where \(p = 8\) counts all
predictors excluding the intercept, and \(n = 3{,}561\) is the full
cleaned sample. Cook's Distance was then computed for every observation,
using the standard threshold of \(4/n = 4/3{,}561 \approx 0.00112\). In
total, 161 observations exceeded this threshold and were removed. Among
the most influential were observations 2614 (Cook's \(D = 0.0139\)), 212
(Cook's \(D = 0.0100\)), 3032 (Cook's \(D = 0.0041\)), and 2264 (Cook's
\(D = 0.0027\)). To be precise, observations 2264 and 3032 correspond to
one- and two-bedroom Boston apartments listed at \$4,000 and \$3,000 per
night respectively, prices far from market normal that generated
standardized residuals exceeding \(+4.9\) and \(+4.5\), making these
points clear outliers. Observations 373 and 1416, which appear in the
influence plot (Figure 7) as the rightmost points with hat-values of
0.090 and 0.070, were examined but not removed. Since their Cook's \(D\)
values (0.00043 and 0.00019) fall below the removal threshold, and their
standardized residuals are small enough (\(-0.20\) and \(-0.15\)),
indicating that even though they show extreme values, they do not
distort the actual prediction. After removing the 161 influential
observations, the cleaned dataset for the final model contains
\(n = 3{,}400\) observations. The Cook's Distance plot for the final
model (Figure 10) confirms the success of these removals: the maximum
Cook's \(D\) falls from 0.0139 to 0.0022, and the final residual
diagnostics (Figure 9) show improved symmetry in the Residuals
vs.~Fitted plot and better Q-Q alignment relative to Figure 4.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig6-1.pdf}}
\caption{Figure 6: Cook's Distance for all observations in the primary
model. The dashed red line marks the threshold of 4/n = 0.00112.
Observations 212, 1062, and 2614 are the most influential.}
\end{figure}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig7-1.pdf}}
\caption{Figure 7: Influence plot showing hat-values (leverage) on the
x-axis, studentized residuals on the y-axis, and Cook's Distance encoded
as circle size and colour. Observations 373 and 1416 are high leverage
but not influential. Observations 2264 and 3032 are extreme outliers in
Y. Observations 212 and 2614 are genuinely influential.}
\end{figure}

In order to select variables we used backward stepwise selection,
utilizing AIC and BIC as different scoring methods. Results of both
indicated that dropping the host\_is\_superhost predictor would improve
the model. Removing this variable resulted in a reduction of AIC by 1.64
points and BIC by 7.82, meaning that this predictor just added
complexity to the model without improving fit. None of the other
predictors were removed: bedrooms, bathrooms, guests included, property
type, and security deposit were all beneficial to the model,
meaningfully contributing to fit. To confirm the absence of
multicollinearity, VIF were computed for all explanatory variables; all
of them were below 1.52, indicating that our coefficient estimates are
not biased.

\subsection{Section 5: Final Model Inference and
Results}\label{section-5-final-model-inference-and-results}

The final model regresses log-transformed nightly prices on five
predictors: bedroom count, bathroom count, guests included, property
type, and security deposit. The model was fit on 3,400 observations
after removal of influential points. Table 5 presents the estimated
coefficients, standard errors, 95\% confidence intervals, and p-values.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.2111}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1222}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1444}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1444}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0889}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0889}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1000}}@{}}
\caption{Table 5: Final model coefficients, standard errors, 95\%
confidence intervals, p-values, and percentage change in nightly price.
Reference category for property type is Apartment.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Predictor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
95\% CI Lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
95\% CI Upper
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
t-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% Change
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Predictor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
95\% CI Lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
95\% CI Upper
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
t-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% Change
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept & 4.3477 & 0.0274 & 4.2940 & 4.4013 & 158.834 & 0.0000 &
7629.71 \\
Bedrooms & 0.2667 & 0.0150 & 0.2373 & 0.2961 & 17.763 & 0.0000 &
30.57 \\
Bathrooms & 0.1585 & 0.0232 & 0.1130 & 0.2040 & 6.831 & 0.0000 &
17.18 \\
Guests Included & 0.0857 & 0.0094 & 0.0673 & 0.1041 & 9.131 & 0.0000 &
8.95 \\
Condominium vs Apt & 0.0060 & 0.0373 & -0.0671 & 0.0791 & 0.161 & 0.8724
& 0.60 \\
House vs Apt & -0.5275 & 0.0251 & -0.5768 & -0.4783 & -20.992 & 0.0000 &
-41.00 \\
Other vs Apt & -0.1190 & 0.0467 & -0.2105 & -0.0275 & -2.550 & 0.0108 &
-11.22 \\
Security Deposit & 0.0003 & 0.0000 & 0.0002 & 0.0003 & 6.931 & 0.0000 &
0.03 \\
\end{longtable}

\textbf{Coefficient Interpretations.} For a log-response model, a
coefficient \(\hat{\beta}\) represents the estimated average change in
\(\log(\text{price})\) for a one-unit increase in the predictor, holding
all other predictors constant. The corresponding percentage change in
nightly price is \((\exp(\hat{\beta}) - 1) \times 100\%\).

Each additional bedroom is associated with a 30.6\% increase in nightly
price (95\% CI: 26.8\% to 34.5\%, \(p < 0.001\)), holding all other
predictors constant. Bedroom count is associated with the largest
positive effect among the continuous predictors and directly addresses
the capacity dimension of the research question. Each additional
bathroom is independently associated with a 17.2\% price increase (95\%
CI: 12.0\% to 22.6\%, \(p < 0.001\)). The independence of this effect
suggests that guests value bathroom availability as a distinct comfort
signal beyond sleeping capacity. Each additional increase in guest
capacity is associated with an 8.9\% increase in price (95\% CI: 7.0\%
to 10.9\%, \(p < 0.001\)), capturing a third capacity signal that
operates independently of physical room count. Bedroom count and guest
capacity capture different aspects of a listing: guest capacity
represents a hard upper limit on how many people can be accommodated,
whereas bedroom count reflects how that capacity is distributed across
the listing. Collectively, the three capacity predictors address the
research question's capacity dimension: physical size and accommodation
capacity explain a meaningful and consistent portion of price variation
in Boston Airbnb listings.

With respect to property type, houses are priced 41.0\% lower than
comparable apartments (95\% CI: \(-42.3\%\) to \(-39.7\%\),
\(p < 0.001\)). This is the single largest effect in the final model.
Listings in the Other category are priced 11.2\% below apartments
(\(p = 0.011\)). Condominiums show no statistically significant price
difference from apartments (\(\hat{\beta} = 0.006\), \(p = 0.872\), 95\%
CI spanning zero), indicating Boston's condominium market is priced on
par with apartments when physical characteristics are held constant.
This non-result is itself informative: the structural similarity between
apartments and condominiums in an urban market means property type
distinction between these two carries no independent pricing signal. In
contrast, the significantly lower pricing of houses suggests a clear
urban preference for apartments and condominiums in Boston's Airbnb
market.

Focusing on listing characteristics, each additional dollar of security
deposit is associated with a 0.03\% increase in nightly price
(\(p < 0.001\)). While statistically significant, the economic magnitude
is negligible --- a \$100 deposit increase corresponds to only a 2.9\%
price increase. Consistent with Ert et al.~(2016), this likely reflects
security deposit as a proxy for listing quality rather than a direct
pricing mechanism: hosts who charge deposits tend to manage
higher-quality listings, and the deposit captures that latent quality
signal indirectly.

\textbf{Literature Comparison.} The bedroom coefficient of 30.6\% per
bedroom substantially exceeds the 17.8\% reported by Cai et al.~(2019)
for Hong Kong listings. This divergence is interpretable rather than
surprising: Boston's premium housing market, where residential space is
scarce and expensive, means that each additional private bedroom
commands a disproportionately higher return than in higher-density Asian
cities where space constraints are distributed differently across
property types. The finding aligns directionally with Cai et al.~(2019)
--- bedrooms matter --- while the magnitude reflects Boston's specific
market conditions.

The house discount of 41.0\% relative to apartments is directionally
consistent with Gibbs et al.~(2018), who found private rooms and houses
priced 28.3\% to 40.1\% below entire homes in Toronto and Calgary. The
estimate from the final model falls at the upper end of this range,
consistent with the apartment-dominated composition of Boston's
short-term rental market, where 73.4\% of listings are apartments. Our
finding reinforces Gibbs et al.'s (2018) core conclusion that property
type is a primary determinant of Airbnb pricing across North American
urban markets, with the specific magnitude reflecting the relative
scarcity of apartments versus houses in Boston's listing inventory.

The non-significance of superhost status (\(p = 0.548\), dropped in
Section 4) diverges from Almeida et al.~(2025), who found review-based
quality signals to be significant price determinants. This divergence is
consistent with the interpretation offered in the proposal: in Boston's
established Airbnb market, guests rely on physical property attributes
rather than host reputation cues when assessing value. The security
deposit finding aligns with Ert et al.~(2016) in showing that
listing-level quality signals operate through pricing via indirect
proxies rather than host-level reputation mechanisms.

\textbf{Model Performance.} Table 6 summarises performance metrics for
both the primary and final models.

\begin{longtable}[]{@{}lll@{}}
\caption{Table 6: Model performance comparison between the primary model
(6 predictors, n = 3,561) and the final model (5 predictors, n =
3,400).}\tabularnewline
\toprule\noalign{}
Metric & Primary Model & Final Model \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metric & Primary Model & Final Model \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R-squared & 0.2742 & 0.3027 \\
Adjusted R-squared & 0.2726 & 0.3013 \\
AIC & 5942.12 & 5103.43 \\
BIC & 6003.9 & 5158.61 \\
Residual Std. Error & 0.5565 & 0.5118 \\
F-statistic & 167.77 & 210.37 \\
p-value & \textless{} 2.2e-16 & \textless{} 2.2e-16 \\
N & 3561 & 3400 \\
\end{longtable}

The final model achieves an adjusted \(R^2\) of 0.3013, explaining
30.1\% of the variation in log nightly price. The improvement over the
primary model's adjusted \(R^2\) of 0.2726 is attributable primarily to
the removal of influential observations rather than the change in
predictors, which was the expected result, as influential observations
inflate residual variance and suppress \(R^2\). Residual standard error
decreased from 0.5565 to 0.5118, indicating a tighter and more accurate
fit around the regression line. The F-statistic of 210.37
(\(p < 2.2 \times 10^{-16}\)) confirms that the model as a whole is
highly significant --- the five predictors collectively explain a
statistically significant portion of log-price variation. The AIC of
5103.43 and BIC of 5158.61 are lower than the primary model values,
though the direct numerical comparison is approximate since the models
were fit on different sample sizes following outlier removal. An
adjusted \(R^2\) of 0.30 is consistent with the range reported in the
hedonic pricing literature for Airbnb datasets --- Gibbs et al.~(2018)
and Wang and Nicolau (2017) report comparable values --- and reflects
the reality that structural variables alone cannot capture the full
complexity of short-term rental pricing, where unobserved factors such
as neighbourhood, interior quality, entertainment amenities, and listing
photographs contribute substantially to price variation. The final
model's diagnostic plots (Figure 9) show no systematic pattern in
residuals versus fitted values, supporting the linearity assumption, and
the Q-Q plot shows only mild upper-tail deviation consistent with a
small number of high-priced listings that the model moderately
underpredicts.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig8-final-1.pdf}}
\caption{Figure 9: Residual diagnostic plots for the final model. Left:
Residuals vs Fitted showing no systematic pattern, supporting linearity.
Centre: Q-Q plot showing mild upper-tail deviation consistent with a
small number of high-priced listings. Right: Scale-Location showing
improved homoscedasticity relative to the primary model.}
\end{figure}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Final_Project_Submission_files/figure-latex/fig9-final-cooks-1.pdf}}
\caption{Figure 10: Cook's Distance for the final model. The maximum
Cook's D has fallen from 0.0139 in the primary model to 0.0022,
confirming the success of the influential observation removal.}
\end{figure}

\subsection{Section 6: Discussion and
Conclusion}\label{section-6-discussion-and-conclusion}

This study examined the extent to which property type, capacity, and
listing characteristics explain variation in the log-transformed nightly
price of Airbnb listings in Boston. After a rigorous model selection
process, encompassing Box-Cox transformation verification, Cook's
Distance based outlier removal, and backward stepwise variable
selection, the final linear regression model was fit on 3,400
observations with five predictors: bedroom count, bathroom count, guest
capacity, property type, and security deposit. The model achieves an
adjusted \(R^2\) of 0.3013 and an F-statistic of 210.37
(\(p < 2.2 \times 10^{-16}\)), confirming that the predictors
collectively explain a statistically significant and meaningful portion
of log-price variation. The central conclusion of this analysis is that
physical capacity is the dominant driver of Airbnb nightly prices in
Boston, consistent with hedonic pricing theory and prior literature.

The most substantive finding concerns the magnitude and independence of
three capacity predictors. Each additional bedroom is associated with a
30.6\% increase in nightly price, ceteris paribus (95\% CI: 26.8\% to
34.5\%, \(p < 0.001\)). This estimate exceeds the 17.8\% per-bedroom
premium reported by Cai et al.~(2019) in Hong Kong, a difference that
can be explained by Boston's premium urban real estate market and the
relative scarcity of larger multi-bedroom listings. Similarly, each
additional bathroom is associated with a 17.2\% price increase (95\% CI:
12.0\% to 22.6\%, \(p < 0.001\)), reflecting the value guests assign to
comfort and privacy. Guest accommodation capacity also exhibits a
significantly positive association with price, consistent with Wang and
Nicolau's (2017) analysis showing that larger properties command higher
rates. Each unit increase in guest capacity is associated with an 8.9\%
price increase (95\% CI: 7.0\% to 10.9\%, \(p < 0.001\)). Taken
together, these capacity-related findings confirm that physical scale is
a primary driver of Airbnb pricing in Boston, in line with the broader
hedonic pricing literature (Gibbs et al., 2018).

The role of property type reveals an interesting pattern in the Boston
market. Houses are priced 41.0\% lower than apartments (95\% CI:
\(-42.3\%\) to \(-39.7\%\), \(p < 0.001\)), and listings in the Other
category are priced 11.2\% below apartments (\(p = 0.011\)). The house
discount aligns with Gibbs et al.'s (2018) finding that houses and
private rooms are priced 28.3\% to 40.1\% below entire homes in Toronto
and Calgary. Our 41.0\% estimate sits at the upper end of this range,
consistent with Boston's apartment-dominated nature, where 73.4\% of
listings are apartments. This finding reflects the broader conclusion
that property type is a primary determinant of Airbnb pricing across
North American urban markets (Gibbs et al., 2018), with the specific
magnitude reflecting Boston's relative scarcity of desirable
non-apartment stock in high-demand tourist areas.

The non-significance of superhost status is another notable finding.
Although Almeida et al.~(2025) demonstrates that review-based quality
signals, including superhost designation, positively influence Airbnb
prices in some markets, this effect does not emerge in our Boston
dataset. Superhost status was removed from the model through backward
stepwise selection, as dropping it reduced AIC by 1.64 points and BIC by
7.82, showing that it added complexity without improving model fit. One
interpretation is that Boston's short-term rental market is sufficiently
mature that guests weigh physical amenities more heavily than
reputational badges when making decisions. Alternatively, superhost
status may have indirect pricing effects that are mediated by listing
quality indicators already captured by other predictors in the model.
Additionally, security deposit retains a small but statistically
significant positive association with price, though its economic
magnitude is negligible --- a \$100 increase in deposit corresponds to
only a 2.9\% price increase. As Ert et al.~ (2016) argued, deposits
serve as a proxy signal for listing quality rather than a direct pricing
mechanism, as hosts managing higher-quality listings tend to charge
deposits.

The final model's adjusted \(R^2\) of 0.3013 represents a meaningful
improvement over the primary model's 0.2726, primarily due to the
removal of 161 influential observations that were inflating residual
variance. The residual standard error fell from 0.5565 to 0.5118,
indicating a tighter fit around the regression line. AIC and BIC are
both lower than in the primary model. Our final adjusted \(R^2\) of
30.1\% is consistent with comparable literature in hedonic pricing,
while remaining variation is attributable to unobserved factors such as
neighbourhood, desirability, seasonal demand, and interior quality. The
diagnostic plots confirm that linearity holds and the Q-Q plot shows
only mild upper-tail deviation, consistent with a small number of
high-priced listings that the model underpredicts.

Based on these findings, several recommendations emerge for hosts,
guests, and policymakers. For hosts, the results indicate that investing
in additional bedrooms and increasing physical capacity has the
strongest potential to justify higher nightly prices. Hosts seeking to
maximise revenue should prioritise listing features that increase
physical capacity, as these have the largest reliable association with
price. For guests, these findings highlight that pricing in Boston
reflects tangible amenities more than reputational signals, suggesting
that careful attention to physical listing details may yield better
value than relying on superhost status alone. From a policy perspective,
the strong relationship between property capacity and price is relevant
to discussions about Airbnb's effect on housing markets. As Barron et
al.~(2020) demonstrate, higher Airbnb activity is associated with
elevated housing costs; the fact that larger units command higher
premiums may incentivise landlords to convert family-sized units into
short-term rentals.

There are several ways in which this analysis could be strengthened in
future studies. First, the current model explains only 30.1\% of price
variation, indicating that important predictors are absent.
Incorporating neighbourhood-level variables such as proximity to
transit, tourist attractions, or high-demand areas could improve
explanatory power. Spatial regression techniques or neighbourhood fixed
effects would allow the model to account for geographic clustering of
high-priced listings. Second, the dataset is cross-sectional, which
prevents analysis of how pricing varies by season, major events, or
changes in the broader rental market. A longitudinal design
incorporating time fixed effects would enable more nuanced causal
inference. Third, the inclusion of review scores, review count, and host
response rate as additional predictors would allow a more direct test of
whether reputation-based signals influence pricing in Boston, rather
than relying on superhost status as a blunt proxy. Finally, expanding
the sample to include listings from multiple cities, following the
approach of Wang and Nicolau (2017), would allow for cross-market
comparisons that could illuminate whether Boston's distinctive patterns
--- the lower relative pricing of houses and the insignificance of
superhost status --- generalise to other urban markets.

In conclusion, this study provides empirical evidence that physical
capacity characteristics --- specifically bedroom count, bathroom count,
and guest accommodation --- are the primary drivers of nightly price
variation among Boston Airbnb listings. These results are broadly
consistent with hedonic pricing literature while also revealing
market-specific patterns, most notably the strong house discount
relative to apartments and the limited pricing influence of superhost
status. These findings contribute to a growing body of evidence that
Airbnb pricing reflects underlying property attributes in predictable
ways, while demonstrating that city-level context meaningfully shapes
which attributes matter most. Future work incorporating reputation-based
variables and neighbourhood-level controls has strong potential to
deepen this understanding and narrow the gap between model predictions
and observed listing prices.

\subsection{Section 7: Author
Contributions}\label{section-7-author-contributions}

\textbf{Omar Shahata:} Co-authored Section 3 (Primary Model Results and
Diagnostics), including statistical interpretation of the preliminary
model coefficients and residual diagnostic analysis. Co-authored Section
5 (Final Model Inference and Results), contributing to the coefficient
table presentation and model performance discussion.

\textbf{Arya Badal Kalarickal:} Developed and maintained all R scripts
for the final analysis pipeline, including data cleaning, exploratory
data analysis, primary model fitting, diagnostic analysis, model
selection, and final model inference. Contributed to the writing of
Section 3 (Primary Model) and Section 4 (Model Selection), including the
influential observation analysis and variable selection procedures.
Wrote Section 5 (Final Model Inference and Results), including all
coefficient interpretations, literature comparisons, and model
performance assessment.

\textbf{Polyna German:} Authored the introduction of the dataset and
predictor variable descriptions, and created all corresponding
visualizations in Section 2 (Data Description). Contributed to the
writing of Section 4 (Model Selection), including the influential
observation analysis, outlier identification and justification using
Cook's Distance, interpretation of variable selection results,
referencing and interpreting created graphs, and revising the
statistical writing for precision and consistency. Also contributed to
the References section.

\textbf{Riley Fewer:} Authored the Introduction (Section 1), including
the research question, literature review connecting three peer-reviewed
sources to the research question, and justification for linear
regression as the analytical approach. Also authored the Discussion and
Conclusion (Section 6), synthesizing key findings, situating results
within the existing literature, providing recommendations for hosts,
guests, and policymakers, and outlining directions for future research.

\subsection{Section 8: References}\label{section-8-references}

Almeida, A., Nunes, A. P., \& Machado, L. P. (2025). How do reviews
impact Airbnb's prices? A hedonic approach. \emph{Tourism and
Hospitality}, \emph{6}(4), 181.
\url{https://doi.org/10.3390/tourhosp6040181}

Barron, K., Kung, E., \& Proserpio, D. (2020). The effect of
home-sharing on house prices and rents: Evidence from Airbnb.
\emph{Marketing Science}, \emph{40}(1), 23--47.
\url{https://doi.org/10.1287/mksc.2020.1227}

Cai, Y., Zhou, Y., Ma, J., \& Scott, N. (2019). Price determinants of
Airbnb listings: Evidence from Hong Kong. \emph{Tourism Analysis},
\emph{24}(2), 227--242.
\url{https://doi.org/10.3727/108354219x15525055915554}

Ert, E., Fleischer, A., \& Magen, N. (2016). Trust and reputation in the
sharing economy: The role of personal photos in Airbnb. \emph{Tourism
Management}, \emph{55}, 62--73.
\url{https://doi.org/10.1016/j.tourman.2016.01.013}

Gibbs, C., Guttentag, D., Gretzel, U., Morton, J., \& Goodwill, A.
(2018). Pricing in the sharing economy: A hedonic pricing model applied
to Airbnb listings. \emph{Journal of Travel \& Tourism Marketing},
\emph{35}(1), 46--56.
\url{https://doi.org/10.1080/10548408.2017.1308292}

Wang, D., \& Nicolau, J. L. (2017). Price determinants of sharing
economy based accommodation rental: A study of listings from 33 cities
on Airbnb.com. \emph{International Journal of Hospitality Management},
\emph{62}, 120--131. \url{https://doi.org/10.1016/j.ijhm.2016.12.007}

Boston Airbnb Open Data. (n.d.). \emph{Boston Airbnb open data} {[}Data
set{]}. Kaggle. Retrieved February 1, 2026, from
\url{https://www.kaggle.com/datasets/airbnb/boston}

Inside Airbnb. (n.d.). \emph{About Inside Airbnb: Mission and data
collection description}. Retrieved February 1, 2026, from
\url{https://insideairbnb.com/about/}

Inside Airbnb. (n.d.). \emph{Data assumptions: How the data were
compiled and processed}. Retrieved February 1, 2026, from
\url{https://insideairbnb.com/data-assumptions/}

Airbnb. (n.d.). \emph{What's required to be a Superhost}. Retrieved
February 1, 2026, from \url{https://www.airbnb.ca/help/article/829}

\end{document}
